### ISSUE TITLE
Add "protocol" argument/property allongside "dir_service"

### ISSUE THREAD

**Issue by cjeanneret** [wavesoftware/puppet-xtreemfs#13]
Hello,

It would be good to add a "protocol" argument/property to the definitions/types/classes taking the `dir_service` argument/property.

It might be cleaner and avoid confusions regarding the current dir_service current usage:
- in configuration file for MRC and OSD
- in command lines for Volume and Mount

The latter will require protocol in case we're using either full-SSL support or only Grid-SSL (authentication only).

Currently, we have to so some bad things like:

``` Puppet
$dir = hiera('xtreemfs::dir_service')
::xtreemfs::volume {'foo':
  ensure      => present,
  dir_service => "<protocol>://${dir}",
  options     => {…},
}
```

Proposal would makes this possible:

``` Puppet
::xtreemfs::volume {'foo':
  ensure      => present,
  dir_service => hiera('xtreemfs::dir_service'),
  protocol    => 'pbrpcs',
  options     => {…},
}
```

In puppet, protocol might be set to "undef", meaning we use the default provider (no need of prefix), and if we set some value, it should concatenate `<protocol>://<dir_service>`

I think the following resources will be affected:
- [x] xtreemfs::mount
- [x] xtreemfs::settings
- [x] xtreemfs::volume
- [x] xtreemfs::role::metadata
- [x] xtreemfs::role::storage

and, of course, related types/providers.

**Comment by cardil** [comment]
Ok. Thats seems okey to me. I will do that before `v0.1.0`

**Comment by cjeanneret** [comment]
great, thanks!

**Comment by cardil** [comment]
Done. I've also splited `dir_service` parameter into `dir_host`, `dir_port` and `dir_protocol`. All are optional.

**Comment by cjeanneret** [comment]
Great, thanks! I'll update my calls in fogstore (doing the specs right now -.-')
