### ISSUE TITLE
Passing options to xtreemfs subcommands

### ISSUE THREAD

**Issue by cjeanneret** [wavesoftware/puppet-xtreemfs#14]
Hello,

In order to get a better "puppet experience", it would be great if the `options` hash doesn't need the "--" nor "-" prefixes for xtreemfs subcommand options.

Currently, we have this form:

``` Puppet
  ::xtreemfs::volume {'foo':
    ensure      => present,
    dir_service => "pbrpcs://${dir_service}",
    options     => {
      '-s'                  => 64,
      '-w'                  => 3,
      '--admin_password' => hiera('xtreemfs::admin_password'),
      '--pkcs12-file-path'  => '/etc/ssl/certs/xtreemfs-client.p12',
      '--pkcs12-passphrase' => hiera('xtreemfs::service_cred::pwd'),
    },
  }
```

The "--" and "-" aren't really convenient, especially when all the other names/parameters we might find in other puppet classes are "simple", without any prefixes.

The types should:
- allow both short and long forms without prefixes
- ensure user doesn't pass prefixed options
- if option name is one char, add "-"
- if option name is more than one char, add "--"

It might be better to refuse short form (readability and uniformity as some option [majority] don't have short form), but that's up to you.

**Comment by cardil** [comment]
I'll do that as you described. And, before `v0.1.0` as it breaks compatibility. I'm wondering about parameter `add_hypens_to_options => true,false` with `true` by default, but I'm not convinced to use it. What do you think?

**Comment by cjeanneret** [comment]
hmm. I'm not sure about the real value of this parameter… Better to hide that in some (really basic) intelligence directly in the types. People might be disturbed by this kind of subtlety.

**Comment by cardil** [comment]
I thought about other solution:

Throw deprecation warning when user pass prefixed options instead of fail. In that way, both forms can be used but non-prefixed will be preferred. What do you think?

**Comment by cardil** [comment]
Done

**Comment by cjeanneret** [comment]
Yep, a deprecation notification instead of "fail" is better, of course! Thanks for fixing it :+1:
