### ISSUE TITLE
Create an init.pp

### ISSUE THREAD

**Issue by cjeanneret** [wavesoftware/puppet-xtreemfs#16]
Hello,

While trying to get my fogstore together, I just stumbled on a rather annoying thing: it seems we cannot tell puppet-xtreemfs to add (or not) the repository when we use only the "client" part, represented by `xtreemfs::volume` and `xtreemfs::mount`

It might be useful to provide a simple "xtreemfs" class we might call like that:

``` Puppet
class {'::xtreemfs':
  add_repo => true|false,
}
```

The content would be simple, something like:

```
class xtreemfs ($add_repo = true) {  
# … add repository at will, maybe allow to set other sources/APT key
}
```

If we don't get that, this mean we'll need to install the repository from elsewhere, maybe using some `xtreemfs::internal::repos` class which is obviously a bad idea, as shown in the head comment…

**Comment by cjeanneret** [comment]
gah, I overlooked the `xtreemfs::settings` sorry.

**Comment by cardil** [comment]
Exaclly :+1:
