### ISSUE TITLE
SSL configuration and JKS management

### ISSUE THREAD

**Issue by cjeanneret** [wavesoftware/puppet-xtreemfs#3]
Hello,

I'll need the full SSL support in xtreemfs for my project (SSL authentication, communication encryption). I'll most probably use some external modules:
- [java_ks](https://github.com/puppetlabs/puppetlabs-java_ks) for JKS management
- [openssl](https://github.com/camptocamp/puppet-openssl) for the certificate generation/conversion part (it will need some changes, but as I'm part of the managers… ;) )

Will you accept PR with those modules involved, or do you prefer I manage the SSL certificates outside of the xtreemfs module?

The configuration itself will be done using augeas, as you already did in the internal::configure::*, thus it might be inserted in this module.
Might be good to provide some wrapper in order to trigger service reloading?

Cheers,

C.

**Comment by cardil** [comment]
There will be working extra param that will accept any configuration option. So i think it will be better to take it seperatly. Module should be build for single purpose.

There is a trigger that you can use to reload the services use:

``` puppet
File['cert.crt'] ~> Anchor['xtreemfs::configure']
```

**Comment by cardil** [comment]
BTW. I will propably change the names for anchors to move then that this will be more obvious for ex.: xtreemfs::service in place of xtreemfs::configure nad so on

**Comment by cjeanneret** [comment]
No problem for me, I'll follow the changes.
