### ISSUE TITLE
Feature: Publish module (v0.6.0) to puppet forge

### ISSUE THREAD

**Issue by cardil** [wavesoftware/puppet-xtreemfs#7]
Make a initial release of `v0.1.0` on puppet forge and in github

**Comment by cardil** [comment]
Released to puppet forge. Install with: `puppet module install wavesoftware-xtreemfs`

https://forge.puppetlabs.com/wavesoftware/xtreemfs

Thanks @cjeanneret for all that testing and good ideas!

**Comment by cjeanneret** [comment]
thank YOU for this useful module!
